In [1]:
%pip install pandasql

Requirement already satisfied: pandasql in .\.venv\Lib\site-packages (0.7.3)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (from pandasql) (2.5.4)
Requirement already satisfied: pandas in .\.venv\Lib\site-packages (from pandasql) (3.0.6)
Requirement already satisfied: sqlalchemy in .\.venv\Lib\site-packages (from pandasql) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas->pandasql) (2026.5)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.venv\Lib\site-packages (from sqlalchemy->pandasql) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

#Modify the path according to where the file is in your filesystem
dataset_path = "data-3.csv" 

df = pd.read_csv(dataset_path)

In [3]:
print("Shape:", df.shape)
print("Data types:")
print(df.dtypes)
print("Missing values:\n", df.isnull().sum())

Shape: (400, 17)
Data types:
dev_budget_usd             int64
marketing_budget_usd       int64
dev_time_months            int64
team_size                  int64
metacritic                 int64
user_score                 int64
genre                        str
platforms_count            int64
is_multiplayer             int64
launch_price_usd           int64
median_playtime_hours    float64
release_month              int64
is_franchise               int64
publisher_size               str
reviews_at_launch          int64
launch_discount          float64
first_year_sales_k       float64
dtype: object
Missing values:
 dev_budget_usd           0
marketing_budget_usd     0
dev_time_months          0
team_size                0
metacritic               0
user_score               0
genre                    0
platforms_count          0
is_multiplayer           0
launch_price_usd         0
median_playtime_hours    0
release_month            0
is_franchise             0
publisher_size           0
reviews_at_launch        0
launch_discount          0
first_year_sales_k       0
dtype: int64

Inspecting the data: column types, missing values, inconsistency.
Column types we got numerical and categorical.
No missing values.
Inconsistencies where checked manually for genre and publisher_size.

In [4]:
import pandasql as ps

# function query(sql) will help us write our SQL queries easily
def query(sql):
    return ps.sqldf(sql, globals())

In [5]:
query("""
SELECT launch_discount AS nr
FROM df
WHERE nr> 0.6 OR nr<0;
""")

Empty DataFrame
Columns: [nr]
Index: []

In [6]:
query("""
SELECT metacritic AS rating
FROM df
WHERE rating>100 OR rating<0;
""")

Empty DataFrame
Columns: [rating]
Index: []

In [7]:
query("""
SELECT user_score AS score
FROM df
WHERE score> 100 OR score<0;
""")

Empty DataFrame
Columns: [score]
Index: []

In [8]:
query("""
SELECT release_month AS release
FROM df
WHERE release>11 OR release<0;
""")

Empty DataFrame
Columns: [release]
Index: []

These SQL queries check whether the values in columns are within the given bounds or not. If the values were outside of the bound, the query would return those certain values. Since there are no rows returned, we know that every value is within the required bounds. The bounds were given by the client.

In [9]:
copy_table = df.copy()
rowsToDrop = []
for i, row in copy_table.iterrows():
    if row["dev_budget_usd"] < 3400000:
        rowsToDrop.append(i)

copy_table.drop(rowsToDrop, inplace=True)
print(copy_table)

     dev_budget_usd  marketing_budget_usd  dev_time_months  team_size  \
3           4610783               3308649               51        155
5           4266193               1274032               57        121
39          6854661               3014742                6         56
53          6499290               1850323                7        131
67          4850363               2396969               31        201
106        10451118               2717298                8        126
111         6127719               3383082               56        118
136         5492024               2783111               23         76
139         5463647                667811               16        116
173         9646383               5174662               10        111
192         4022032                909019               47         80
393         4053803               1333248               58        512

     metacritic  user_score      genre  platforms_count  is_multiplayer  \
3            61          46        rpg                4               0
5            77          83    shooter                3               0
39           71          81  adventure                1               1
53           69          80    shooter                1               0
67           86         100  adventure                2               0
106          75          76    shooter                1               1
111          59          60  adventure                3               0
136          68          72        rpg                2               0
139          56          53  adventure                4               1
173          60          66   strategy                4               0
192          72          75   strategy                3               1
393          42          70     puzzle                3               0

     launch_price_usd  median_playtime_hours  release_month  is_franchise  \
3                  60                   34.7              6             0
5                  60                   28.4             10             1
39                 20                    6.6              1             0
53                 30                   42.7             11             1
67                 50                   21.1             11             0
106                50                   23.1              6             0
111                30                   12.7              6             0
136                50                   15.8              2             0
139                30                   10.3              4             0
173                60                    7.6              8             0
192                50                   10.9              1             1
393                70                    8.1             11             0

    publisher_size  reviews_at_launch  launch_discount  first_year_sales_k
3             tiny              10154             0.33               44.96
5             tiny              63634             0.37              834.96
39           large               2828             0.28               43.36
53          medium              99770             0.35             1248.62
67           small               2127             0.37               48.25
106          large               7317             0.31               58.22
111          small               1308             0.16               12.07
136          small               3006             0.26               52.72
139          giant               1340             0.01                7.26
173          giant               6738             0.56               60.87
192          large             115747             0.51              484.08
393           tiny               3594             0.42               28.31

We made a code that copies the original dataset and saves in that copy the outliers of the data. We chose 3400000 to be the limit for outliers based on the graph we made (graph given in excel). Since only 12 out of 400 games have a budget over 3.4 million, and there is a clear gap after that.

In [10]:
final_copy_table = df.copy()
rowsToDrop = []
for i, row in final_copy_table.iterrows():
    if row["dev_budget_usd"] > 3400000:
        rowsToDrop.append(i)

final_copy_table.drop(rowsToDrop, inplace=True)
print(final_copy_table)

     dev_budget_usd  marketing_budget_usd  dev_time_months  team_size  \
0           1780590                551738               45        112
1           2361029                943574                7         23
2           1976102                829247               37        122
4           1079161                640524               40         49
6           1373599                941903                8         96
..              ...                   ...              ...        ...
395          408942                229168               51        205
396          357485                 72742               22         43
397         1440670                494674               23        122
398          107511                 45800               59        282
399          223897                 49966               23        186

     metacritic  user_score      genre  platforms_count  is_multiplayer  \
0            98         100        rpg                1               1
1            42          51    shooter                1               1
2            81          70   strategy                2               1
4            83          95     puzzle                3               1
6            84          80   strategy                2               0
..          ...         ...        ...              ...             ...
395          74          74   strategy                1               0
396          56          56    shooter                3               0
397          73          83  adventure                3               0
398          80          80    shooter                4               1
399          88          92        rpg                2               0

     launch_price_usd  median_playtime_hours  release_month  is_franchise  \
0                  60                   10.1              5             0
1                  30                    9.7              6             0
2                  70                   21.6              4             0
4                  50                    6.1              3             0
6                  70                   13.4              6             0
..                ...                    ...            ...           ...
395                50                   15.2              5             0
396                20                   31.2              6             0
397                60                    8.3              9             0
398                70                    6.3              4             0
399                50                   11.2              3             0

    publisher_size  reviews_at_launch  launch_discount  first_year_sales_k
0            giant               8915             0.18               45.18
1            small               1009             0.45               10.16
2             tiny               6805             0.47               26.65
4            giant               2459             0.49               19.88
6             tiny               1503             0.36               14.13
..             ...                ...              ...                 ...
395         medium                909             0.23                7.20
396          large               3018             0.02               18.75
397          small               4844             0.57               27.67
398          giant               2351             0.20               14.39
399         medium               2006             0.47               15.44

[388 rows x 17 columns]

In the code above we delete the earlier identified outliers. Originally we had 400 rows, now we have 388, meaning we deleted all 12 outliers. However, we did not modify the original data, instead we made a copy specifically for this project.

In [11]:
query("""
SELECT genre, AVG(first_year_sales_k)
FROM final_copy_table
GROUP BY genre;
""")

       genre  AVG(first_year_sales_k)
0  adventure                23.621250
1     puzzle                18.023784
2        rpg                75.070000
3    shooter                70.102750
4   strategy                45.897619

In the query above, we average the first_years_sales_k grouped by genre, to see how genre impacts the sales for the games.

In [12]:
query("""
SELECT genre, platforms_count, AVG(first_year_sales_k)
FROM final_copy_table
GROUP BY genre, platforms_count;
""")

        genre  platforms_count  AVG(first_year_sales_k)
0   adventure                1                25.991600
1   adventure                2                21.169545
2   adventure                3                23.314444
3   adventure                4                23.461250
4      puzzle                1                10.794737
5      puzzle                2                15.490714
6      puzzle                3                23.716087
7      puzzle                4                20.351111
8         rpg                1                79.429565
9         rpg                2                45.968000
10        rpg                3               128.893571
11        rpg                4                67.179375
12    shooter                1                82.356111
13    shooter                2                53.994118
14    shooter                3                76.082069
15    shooter                4                62.595625
16   strategy                1                44.736957
17   strategy                2                50.838750
18   strategy                3                43.643636
19   strategy                4                43.077333

In the query above, we average the first_years_sales_k grouped by genre and platform_count, to see how genre and platform_count impacts the sales for the games.

In [13]:
query("""
SELECT 
  CASE 
    WHEN median_playtime_hours < 10 THEN 'Low (<10)'
    WHEN median_playtime_hours BETWEEN 10 AND 40 THEN 'Medium (10-40)'
    WHEN median_playtime_hours BETWEEN 40 AND 50 THEN 'High (40-50)'
    ELSE 'Very High (>50)'
  END AS median_playtime_hours_band,
ROUND(AVG(first_year_sales_k), 2) AS avg_first_year_sales_k
FROM final_copy_table
GROUP BY median_playtime_hours_band
ORDER BY avg_first_year_sales_k DESC;
""")

  median_playtime_hours_band  avg_first_year_sales_k
0               High (40-50)                   99.30
1             Medium (10-40)                   45.50
2                  Low (<10)                   44.95
3            Very High (>50)                   44.12

In the query above, we average the first_years_sales_k grouped by median_playtime_hours_band, to see how that impacts the sales.